import "@/styles/globals.css";
import { Inter } from "next/font/google";
import Provider from "@/redux/provider";
import type { Metadata } from "next";
import { Footer, Navbar } from "@/components/common";
import { Setup } from "@/components/utility";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata= {
  title: "Proplayas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Setup />
          <Navbar />
          <div>{children}</div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
